// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUl8EJqi6U43e9fFnLSWrEEWnoqS7un5g',
    appId: '1:186892863700:web:95320fc02a972c40c4d341',
    messagingSenderId: '186892863700',
    projectId: 'fastfood-app-94a23',
    authDomain: 'fastfood-app-94a23.firebaseapp.com',
    storageBucket: 'fastfood-app-94a23.firebasestorage.app',
    measurementId: 'G-E164TD8N4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlRdeReqFZePObuY1UOqD_uP0zHYPmZug',
    appId: '1:186892863700:android:b58c11410636623ac4d341',
    messagingSenderId: '186892863700',
    projectId: 'fastfood-app-94a23',
    storageBucket: 'fastfood-app-94a23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB--a-4g6HNcG6BI7mpO8F3I1k2tbqZiYM',
    appId: '1:186892863700:ios:ca21e2f787970c3ac4d341',
    messagingSenderId: '186892863700',
    projectId: 'fastfood-app-94a23',
    storageBucket: 'fastfood-app-94a23.firebasestorage.app',
    iosBundleId: 'com.umarDev.fastfoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB--a-4g6HNcG6BI7mpO8F3I1k2tbqZiYM',
    appId: '1:186892863700:ios:ca21e2f787970c3ac4d341',
    messagingSenderId: '186892863700',
    projectId: 'fastfood-app-94a23',
    storageBucket: 'fastfood-app-94a23.firebasestorage.app',
    iosBundleId: 'com.umarDev.fastfoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUl8EJqi6U43e9fFnLSWrEEWnoqS7un5g',
    appId: '1:186892863700:web:fdd1a2242d9ac980c4d341',
    messagingSenderId: '186892863700',
    projectId: 'fastfood-app-94a23',
    authDomain: 'fastfood-app-94a23.firebaseapp.com',
    storageBucket: 'fastfood-app-94a23.firebasestorage.app',
    measurementId: 'G-5MVK95MJ29',
  );
}
